name: Davewashere.com
favicon: null
layout_spectrum: 0.41423
typography_spectrum: 0.926591725088656
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6f6f6f'
    - '#d6d6d6'
    - '#000000'
    - '#292929'
    - '#ffffff'
  brandStrength: 0.5336870236787945
  lightness: 0.43586684926413
  saturation: 0.5592982799280435
  rhythmicContrast: 0.2205646864604205
purpose: []
